### ISSUE TITLE
uninitialized constant GeoIP

### ISSUE THREAD

**Issue by vitobotta** [cjheath/geoip#13]
Hi, I am trying to use this gem in an app, but for some reason the GeoIP class cannot be found:

ree-1.8.7-2011.03 :001 > require 'geoip'
 => true 
ree-1.8.7-2011.03 :002 > GeoIP
NameError: uninitialized constant GeoIP
    from (irb):2

Am I missing something?

Many thanks in advance
Vito

**Comment by rtyler** [comment]
I believe this issue could be closed :smile_cat:
