### ISSUE TITLE
include LICENSE file in geoip gem

### ISSUE THREAD

**Issue by ktdreyer** [cjheath/geoip#34]
Hi Clifford,

Thank you very much for your work on geoip. I'm working on packaging this gem for Fedora, and the Fedora Packaging Guidelines suggest that I ask you to include a LICENSE file in the root of the project. By including a copy of the exact LGPL license text, you will make the terms of the geoip license very clear.

Also, in the specific case of geoip's LGPL license, all derivative copies of geoip are required to contain the full text of the LGPL license (as alluded in the sentence in README.rdoc: "You should have received a copy of the GNU Lesser General Public License along with this library...") So in order to ease development and distribution of geoip, it makes sense to simply include this text in the upstream project.

More details about this can be found on Fedora's wiki, under the "License Text" section: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

Would you mind adding a LICENSE file with the LGPL license text to the git repo and the gem?

**Comment by rtyler** [comment]
I can confirm that with 1.6.4 the LICENSE file is present, and this can be closed :smile_cat:
