### ISSUE TITLE
Include CHANGELOG file to this gem

### ISSUE THREAD

**Issue by giedriusr** [cjheath/geoip#54]
This file is very important to keep track of changes for this gem.

**Comment by cjheath** [comment]
The git log has the true history. CHANGELOGs almost always lie.

**Comment by giedriusr** [comment]
Agree and disagree. http://keepachangelog.com
>Why can’t people just use a git log diff?
Because log diffs are full of noise — by nature. They could not make a suitable change log even in a hypothetical project run by perfect humans who never make typos, never forget to commit new files, never miss any part of a refactoring. The purpose of a commit is to document one atomic step in the process by which the code evolves from one state to another. The purpose of a change log is to document the noteworthy differences between these states.

>As is the difference between good comments and the code itself, so is the difference between a change log and the commit log: one describes the why, the other the how.
