### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - GeoIP.dat

### ISSUE THREAD

**Issue by acegilz** [cjheath/geoip#56]
```
2.1.1 :003 > c = GeoIP.new('GeoIP.dat').country('www.nokia.com')
Errno::ENOENT: No such file or directory @ rb_sysopen - GeoIP.dat
```
I downloaded the GeoIP.dat but where should it be placed??

**Comment by acegilz** [comment]
Allright.. should be more clear here is the answer:
http://stackoverflow.com/questions/1988049/getting-a-user-country-name-from-originating-ip-address-with-ruby-on-rails

**Comment by cjheath** [comment]
GeoIP has no preferences about where you put the file. Put it wherever you like. Just make sure that you tell GeoIP the right path to it.
