### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by Emile-Filteau** [cjheath/geoip#57]
Hey, just wondering if you are planning to make a new release soon ?

@cjheath

**Comment by cjheath** [comment]
What did you have in mind? I don't have code (or time to write code) to handle the new Maxmind 2 format. The other implementations are open source. If someone wants to rewrite the core into Ruby, I'll happily accept a PR and republish, I just don't have time to write it myself.

**Comment by Nowaker** [comment]
@cjheath What he (probably) meant is just to release what's on master. Better to have it released than have good code stay there on master.

**Comment by cjheath** [comment]
Done.

**Comment by ktdreyer** [comment]
Mind pushing the Git tag as well? https://github.com/cjheath/geoip/issues/66

**Comment by Nowaker** [comment]
Thank you @cjheath, I appreciate this!

**Comment by Emile-Filteau** [comment]
Nice ! Thank you very much.
