### ISSUE TITLE
utf-8 read incorrect

### ISSUE THREAD

**Issue by diida** [cjheath/geoip#58]
I converts MaxMind CSV files to .dat files use 
https://github.com/mteodoro/mmutils/blob/master/csv2dat.py 
And translate some city name to local language（Fuzhou=> Fuzhou福州）before convert.

```ruby
# encoding: UTF-8
require "geoip"
@database="mmcity.dat"
geoip_initialize = ::GeoIP.new(@database)
info=geoip_initialize.city("218.85.*.*")
print info.city_name

# output Fuzhouç¦å·
```
I modify some code in "geoip.rb"
line 781
```ruby
# city = city.force_encoding('iso-8859-1').encode('utf-8') if city.respond_to?(:force_encoding)
city.force_encoding(Encoding::UTF_8) # add this just for [logstash geoip filter ](https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb) line 192

#output：Fuzhou福州
```

Test on jruby 1.9 in logstash and ruby 2.0.0

**Comment by cjheath** [comment]
The CSV files and the GeoIP database are not UTF-8. They are in fact Latin-1 (ISO-8859-1), which is what my code enforces.

You have added UTF-8, so you have produced a non-standard GeoIP database file, and you need your non-standard code to read it correctly.
