### ISSUE TITLE
missing 1.6.3 version tag in GitHub

### ISSUE THREAD

**Issue by ktdreyer** [cjheath/geoip#66]
Mind pushing the `v1.6.3` Git tag to GitHub?

**Comment by cjheath** [comment]
Done

**Comment by cjheath** [comment]
I've never actually *used* a git tag, so I'm curious what you use them for?

**Comment by ktdreyer** [comment]
Sure, I rely on the Git tags when I maintain the Fedora rubygem-geoip package. There are tools that let me update the packaging quickly [(rdopkg)](https://github.com/openstack-packages/rdopkg) and these work with Git tags. It's also useful to use `git log <tag1>..<tag2>` to look through the change log for regressions.  I might develop patches to get geoip to build with the latest Ruby versions, and it's useful to develop those on Git tags to I can test them out prior to pushing PRs for master.

**Comment by cjheath** [comment]
Good to know, thanks. I don't (any longer) have Rakefile automation for releasing, and this persuades me I should (re-)build it. (geoip is a *very* old gem!)
