### ISSUE TITLE
Why is the latitude/longitude an empty string?

### ISSUE THREAD

**Issue by jameshfisher** [cjheath/geoip#69]
What's going on with these lines?:

https://github.com/cjheath/geoip/blob/edac76c7ee3cbe58b67d33bf8ada1eb5bc6fda47/lib/geoip.rb#L801
https://github.com/cjheath/geoip/blob/edac76c7ee3cbe58b67d33bf8ada1eb5bc6fda47/lib/geoip.rb#L810

This seems rather unidiomatic - a better value would be `nil`. The occasional appearance of "empty string" coordinate components caused a bit of confusion for us!

**Comment by cjheath** [comment]
The answers are lost in the mist of time, unfortunately, but I suspect the answer was in Feb 2005, when I wrote the first pure Ruby version matching Sean Chittendon's C extension. The longitude setting was definitely that way when I migrated from rubyforge.org to github in October 2007, see https://github.com/cjheath/geoip/blob/53457d8fff67a89a26716d31ab97e4e1e52f0b25/lib/geoip.rb#L340
