### ISSUE TITLE
DATA_DIR incompatible with kali-rolling

### ISSUE THREAD

**Issue by Ma-shellwe** [cjheath/geoip#70]
https://github.com/cjheath/geoip/blob/8760f93a29dcd01f35346b78a905d6fba6ded323/lib/geoip.rb#L64
DATE_DIR should been '/usr/share/ruby-geoip/geoip'

**Comment by cjheath** [comment]
You're welcome to load data from wherever you like, but this is the GeoIP gem and the GeoIP data, so it loads from within the gem. As it should.
