### ISSUE TITLE
Version unclear

### ISSUE THREAD

**Issue by snowblink** [cjheath/geoip#74]
I am confused as to what version we are actually on and which one is the latest.

Please could you clarify?

From rubygems
> 1.6.4 - August 03, 2016 (64.5 KB)
1.6.3 - January 07, 2017 (65 KB)
1.6.2 - August 03, 2016 (65 KB)
1.6.1 - June 24, 2015 (65 KB)
1.5.0 - March 10, 2015 (65 KB)

From https://github.com/cjheath/geoip/blob/master/geoip.gemspec
1.6.2

https://github.com/cjheath/geoip/releases
1.6.3

https://github.com/cjheath/geoip/blob/master/lib/geoip.rb
1.6.4

**Comment by cjheath** [comment]
It's 1.6.4 - I forgot to push the gemspec the last 2 releases.
I have never purposely pushed a Github release, but I suspect the difference is in whether I do `rake release` or `rake build; gem push ...`.
