### ISSUE TITLE
test/csvORG2dat.py does not support python3

### ISSUE THREAD

**Issue by pterjan** [cjheath/geoip#77]
I don't think this affects anyone else than the maintainer but:

```
  File "/csvORG2dat.py", line 139
    print node.segment, [self.dump_node(node.lhs), self.dump_node(node.rhs)]
          ^
SyntaxError: invalid syntax
```

**Comment by cjheath** [comment]
... and doesn't really affect the maintainer either :)
Thanks for the report. If I remember what this code does and I need it, I guess I'll have to fix it!
