### ISSUE TITLE
Reporting Abuse on GeoIP

### ISSUE THREAD

**Issue by thowellmm** [cjheath/geoip#78]
Hello,

I found your contact information on [this website](https://rubygems.org/gems/geoip/versions/1.6.4).

GeoIP and GeoIP2 are registered trademarks of MaxMind, Inc. Trademark number 2897141. The usage of MaxMind's trademark on this website is infringing on our trademark rights. We ask that you remove this usage from your website and any related collateral.

Thank you,
Tristen Howell
Operations Associate
MaxMind, Inc.

**Comment by thowellmm** [comment]
Hello,

Please disregard my previous comment. I am mistaken.

Thank you for writing the RubyGem.

Tristen Howell
Operations Associate
MaxMind, Inc.

**Comment by cjheath** [comment]
I am glad that you don't mind people contributing freely to increasing the value of *your* product.
